package com.example.cafemangmentsystem.license;

import com.example.cafemangmentsystem.common.entity.BaseEntity;
import com.example.cafemangmentsystem.tenant.entity.SubscriptionPlan;
import jakarta.persistence.*;
import lombok.*;

import java.time.Instant;

/**
 * Platform-level entity — NOT tenant-scoped. A license key is generated by the
 * platform owner and given to a customer. When activated it is linked to a tenant.
 */
@Entity
@Table(name = "license_keys")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class LicenseKey extends BaseEntity {

    @Column(name = "license_key", nullable = false, unique = true, length = 32)
    private String key;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private SubscriptionPlan plan;

    /** How many tenants can activate this key (normally 1). */
    @Column(name = "max_activations", nullable = false)
    @Builder.Default
    private int maxActivations = 1;

    @Column(name = "activations_count", nullable = false)
    @Builder.Default
    private int activationsCount = 0;

    /** When this key expires (null = never). */
    @Column(name = "expires_at")
    private Instant expiresAt;

    /** Tenant that activated this key (null = not yet activated). */
    @Column(name = "activated_by_tenant_id")
    private Long activatedByTenantId;

    @Column(name = "activated_at")
    private Instant activatedAt;

    /** Optional note for the platform admin (e.g. customer name, order id). */
    @Column(length = 500)
    private String notes;

    @Column(nullable = false)
    @Builder.Default
    private boolean revoked = false;

    public boolean isFullyActivated() {
        return activationsCount >= maxActivations;
    }

    public boolean isExpired() {
        return expiresAt != null && Instant.now().isAfter(expiresAt);
    }

    public boolean isUsable() {
        return !revoked && !isExpired() && !isFullyActivated();
    }

    public String getKey() { return key; }
    public void setKey(String key) { this.key = key; }

    public SubscriptionPlan getPlan() { return plan; }
    public void setPlan(SubscriptionPlan plan) { this.plan = plan; }

    public int getMaxActivations() { return maxActivations; }
    public void setMaxActivations(int maxActivations) { this.maxActivations = maxActivations; }

    public int getActivationsCount() { return activationsCount; }
    public void setActivationsCount(int activationsCount) { this.activationsCount = activationsCount; }

    public Instant getExpiresAt() { return expiresAt; }
    public void setExpiresAt(Instant expiresAt) { this.expiresAt = expiresAt; }

    public Long getActivatedByTenantId() { return activatedByTenantId; }
    public void setActivatedByTenantId(Long activatedByTenantId) { this.activatedByTenantId = activatedByTenantId; }

    public Instant getActivatedAt() { return activatedAt; }
    public void setActivatedAt(Instant activatedAt) { this.activatedAt = activatedAt; }

    public String getNotes() { return notes; }
    public void setNotes(String notes) { this.notes = notes; }

    public boolean isRevoked() { return revoked; }
    public void setRevoked(boolean revoked) { this.revoked = revoked; }
}
